source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2
zplug "zdharma-continuum/history-search-multi-word", defer:2

zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
zplug "plugins/git",   from:oh-my-zsh
#zplug "themes/gnzh",   from:oh-my-zsh, as:theme
zplug "jezek/3e2b3b9ed350084ccde97f8be8c7a88f", \
    from:gist, \
    as:theme, \
    use:jezek.zsh-theme 
#
# Install plugins if there are plugins that have not been installed
if ! zplug check; then
	zplug install
fi

# Then, source plugins and add commands to $PATH
zplug load

if zplug check zsh-users/zsh-history-substring-search; then
  bindkey '^[[1;5A' history-substring-search-up
  bindkey '^[[1;5B' history-substring-search-down
fi

if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi

# Add history search to ctrl+/
if zplug check zdharma-continuum/history-search-multi-word; then
	bindkey "^_" history-search-multi-word
fi

# so as not to be disturbed by Ctrl-S ctrl-Q in terminals:
stty -ixon

# Change color of comments to make them visible ob black transparent background
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=#545652'
