#! /bin/bash
if [ -z ${dotfilesDir+x} ]; then
	source "$HOME/.dotfiles/installers/install.sh" essentials "$@"
fi

dotBackupDir="${dotfilesDir}/backup"
if [ ! -d $dotBackupDir ]; then
	echo -e $cErr"Backup config directory does not exist: "$cFile${dotBackupDir}$cNone
	echo -e "Run backup install, to configure: "$cFile${dotfilesDir}"/installers/backup/install.sh"$cNone
	exit 1
fi

rib="${dotfilesDir}/installers/backup/rsync-incremental-backup/rsync-incremental-backup-remote"

if [ ! -f $rib ]; then
	echo -e $cErr"External backup script file not found: "$cFile${rib}$cNone
	exit 1
else
	if [ ! -x $rib ]; then
		echo -e $cErr"External backup script file is not executable: "$cFile${rib}$cNone
		exit 1
	fi
fi

if ! .needCommand rsync scp ssh; then
	exit 2
fi

#TODO use config generated by install in backup dir.
#TODO check mountpoints in source and warn if there is a mount pint not in excludes
#TODO fork & rewrite rsync-incremental-backup to pass variables as parameters, or set parameters from enviroment
#TODO backup more directories
( cd $dotBackupDir ; pwd ; .run "${rib} '${HOME}/Programy' '/home/jezek/Zálohy/jEzShiBook/rib' 'jezek@192.168.88.132'" )
